### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by BTruer** [revan/RU-Food-Scraper#7]
Hi Revan and others,

I am trying to use your api at: http://vps.rsopher.com/nutrition.json  and I get a good response (200) but nothing is returning meaning I get nothing or empty.

I took a look at http://menuportal.dining.rutgers.edu/foodpro/pickmenu.asp?sName=Rutgers+University+Dining&locationNum=04&locationName=Busch+Dining+Hall&naFlag=1

and it looks like they have problems as well. Could this be because of their service? When I tried to run your scrape.py I get:
` File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error`

Any thoughts?

Thank you!

**Comment by revan** [comment]
Hm weird, I can't check the site from here (tells me it's blocked by
administrator, might be because of my Cambodian IP). Can take a look when
I'm back in the country.

If you're having trouble accessing the site too though, then no surprise
that the scraper is broken -- did they maybe change the URL?

**Comment by revan** [comment]
Seems to be working fine now, so it was probably just upstream issues.
